version: "3"
services:
  node-app:
    build: . 
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000      
    depends_on:
      - mongo
  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alex
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db-fcc:/data/db
  redis: 
    image: redis 
volumes: 
  mongo-db-fcc: